In [1]:
import numpy as np

text = "What are the symptoms of diabetes?"
words = text.split()

print("Input Tokens:")
print(words)
print()

Input Tokens:
['What', 'are', 'the', 'symptoms', 'of', 'diabetes?']



In [2]:
embedding_size = 8
attention_dim = 4

np.random.seed(7)
length = len(words)
X = np.random.randn(length, embedding_size)

print("Embedding Shape:", X.shape)
print()

Embedding Shape: (6, 8)



In [3]:
Wq = np.random.randn(embedding_size, attention_dim)
Wk = np.random.randn(embedding_size, attention_dim)
Wv = np.random.randn(embedding_size, attention_dim)

Q = np.dot(X, Wq)
K = np.dot(X, Wk)
V = np.dot(X, Wv)

scores = np.dot(Q, K.T)
scaled_scores = scores / np.sqrt(attention_dim)

def softmax(matrix):
    shifted = matrix - np.max(matrix, axis=1, keepdims=True)
    exp_values = np.exp(shifted)
    return exp_values / np.sum(exp_values, axis=1, keepdims=True)

attention = softmax(scaled_scores)
context_vectors = np.dot(attention, V)

In [4]:
print("Scaled Attention Scores:")
print(np.round(scaled_scores, 3))

print("\nAttention Weights:")
print(np.round(attention, 4))

print("\nContextual Representations:")
print(np.round(context_vectors, 4))

Scaled Attention Scores:
[[ -5.098  -4.27   -4.048  -6.52    8.923  13.939]
 [ -3.826  -2.428   0.69   -1.123   2.211   5.674]
 [  9.096   4.653   4.852   8.386  -5.487 -15.807]
 [  6.51    4.258   9.34   10.428 -13.245 -14.517]
 [  3.413   0.532  13.738  10.001 -13.892  -2.146]
 [  7.015   4.078  12.094   9.875 -20.802  -8.033]]

Attention Weights:
[[0.000e+00 0.000e+00 0.000e+00 0.000e+00 6.600e-03 9.934e-01]
 [1.000e-04 3.000e-04 6.600e-03 1.100e-03 3.010e-02 9.619e-01]
 [6.589e-01 7.700e-03 9.500e-03 3.239e-01 0.000e+00 0.000e+00]
 [1.460e-02 1.500e-03 2.479e-01 7.359e-01 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 9.767e-01 2.330e-02 0.000e+00 0.000e+00]
 [5.600e-03 3.000e-04 8.967e-01 9.750e-02 0.000e+00 0.000e+00]]

Contextual Representations:
[[-1.5588 -0.7867  0.1027  1.17  ]
 [-1.5605 -0.8142 -0.0155  1.0801]
 [ 1.701   0.532  -0.0322 -0.2254]
 [ 0.6735  0.8715 -0.4861 -4.1641]
 [ 0.6318  0.8611 -2.7684 -3.5246]
 [ 0.6428  0.8601 -2.5196 -3.5686]]
